<a href="https://colab.research.google.com/github/saqqad00-pixel/python-learning-journey/blob/main/final_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
saad=pd.read_csv("/content/traffic.csv")
saad

,Time,Date,Day of the week,CarCount,BikeCount,BusCount,TruckCount,Total,Traffic Situation
0,12:00:00 AM,10,Tuesday,31.0,0,4,4,39.0,low
1,12:15:00 AM,10,Tuesday,49.0,0,3,3,55.0,low
2,12:30:00 AM,10,Tuesday,46.0,0,3,6,55.0,low
3,12:45:00 AM,10,Tuesday,51.0,0,2,5,58.0,low
4,1:00:00 AM,10,Tuesday,57.0,6,15,16,94.0,normal
...,...,...,...,...,...,...,...,...,...
3071,10:45:00 PM,9,Thursday,16.0,3,1,36,56.0,normal
3072,11:00:00 PM,9,Thursday,11.0,0,1,30,42.0,normal
3073,11:15:00 PM,9,Thursday,15.0,4,1,25,45.0,normal
3074,11:30:00 PM,9,Thursday,16.0,5,0,27,48.0,normal
3075,11:45:00 PM,9,Thursday,14.0,3,1,15,33.0,normal

In [5]:
saad.dtypes

Time                  object
Date                   int64
Day of the week       object
CarCount             float64
BikeCount              int64
BusCount               int64
TruckCount             int64
Total                float64
Traffic Situation     object
dtype: object

In [6]:
saad.isnull().sum()

Time                  0
Date                  0
Day of the week       0
CarCount             21
BikeCount             0
BusCount              0
TruckCount            0
Total                19
Traffic Situation    17
dtype: int64

In [15]:
saad["CarCount"].fillna(saad["CarCount"].mean(),inplace=True)
saad["Total"].fillna(saad["Total"].mean(),inplace=True)
saad['Traffic Situation'].fillna(saad["Traffic Situation"].mode(),inplace=True)

/tmp/ipykernel_6676/422164612.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  saad["CarCount"].fillna(saad["CarCount"].mean(),inplace=True)
/tmp/ipykernel_6676/422164612.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  saad["Total"].fillna(saad["Total"].mean(),inplace=True)
/tmp/ipykernel_6676/422164612.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  saad['Traffic Situation'].fillna(saad["Traffic Situation"].mode(),inplace=True)

In [7]:
saad.isnull().sum().sum()

np.int64(57)

In [8]:
saad.shape

(3076, 9)

In [12]:
saad.dropna(inplace=True)